name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour, change as needed

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # fetch full history for pull/rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install praw requests

      - name: Run bot
        run: |
          python ./bot.py

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git pull --rebase origin main || true
          git add subreddit_refs.csv
          git commit -m "Update subreddit_refs.csv [auto]" || true
          git push origin main || true

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: subreddit_refs
          path: subreddit_refs.csv
          retention-days: 14

