name: Run Reddit Bot

on:
  schedule:
    - cron: "*/30 * * * *"   # run every 30 minutes
  workflow_dispatch:          # allow manual run from GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install praw

    - name: Run bot (max 10 minutes)
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
      run: timeout 600 python ./bot.py

    - name: Commit results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add subreddit_refs.csv
        git commit -m "Update subreddit references [skip ci]" || echo "No changes to commit"
        git push

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: subreddit-refs
        path: subreddit_refs.csv
