name: Reddit Scraper Auto-Update

on:
  schedule:
    # Run every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      USER_AGENT: ${{ secrets.USER_AGENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw requests

      - name: Configure Git
        run: |
          git config --global user.name "EpicureanAtom"
          git config --global user.email "miloradovicdragutin@gmail.com"

      - name: Run Reddit scraper
        run: |
          python ./bot.py

      - name: Commit & Push CSV if updated
        run: |
          git add subreddit_refs2.csv
          git diff --cached --quiet || git commit -m "Update subreddit_refs2.csv [auto]"
          git push origin main
