name: Continuous Reddit Bot2

on:
  workflow_dispatch:   # run manually
  schedule:
    - cron: "*/30 * * * *"  # run every 30 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests praw

    - name: Run botabc
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
      run: timeout 1800 python ./bot.py

    - name: Commit updated CSV
      run: |
        git add subreddit_refs2.csv
        git diff --cached --quiet || git commit -m "Update subreddit_refs2.csv [auto]"
        git push || echo "No new changes to push"

    - name: Upload CSV artifact
      uses: actions/upload-artifact@v4
      with:
        name: subreddit-refs2
        path: subreddit_refs2.csv
